name: build
on:
  push:
    branches:
      - master
    paths:
      - vendor/**
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  CONTAINER_URL: https://github.com/${{ github.repository }}

jobs:
  build-changed:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: docker buildx build and push
        run: ./scripts/build-and-push-changed.sh

